language: go

before_install:
  - sudo apt-get install libtool autoconf automake uuid-dev build-essential libsodium-dev
  - wget http://download.zeromq.org/zeromq-4.1.1.tar.gz
  - tar xzf zeromq-4.1.1.tar.gz && pushd zeromq-4.1.1
  - ./configure
  - make && make install
  - popd

script: go test -v .
